### ISSUE TITLE
Segmentation fault in sws_scale

### ISSUE THREAD

**Issue by Nirmal1313** [bartjoyce/video-app#1]
hi @bartjoyce 

when i am trying to render video using 

```
glfwWindowHint(GLFW_OPENGL_FORWARD_COMPAT, GL_TRUE);
        glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);
        glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
        glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 2);
        glfwWindowHint(GLFW_RESIZABLE, GL_FALSE);

        GLFWmonitor *monitor = glfwGetPrimaryMonitor();
        const GLFWvidmode *mode = glfwGetVideoMode(monitor);
        glfwWindowHint(GLFW_RED_BITS, mode->redBits);
        glfwWindowHint(GLFW_GREEN_BITS, mode->greenBits);
        glfwWindowHint(GLFW_BLUE_BITS, mode->blueBits);
        glfwWindowHint(GLFW_REFRESH_RATE, mode->refreshRate);
        GLFWwindow *window = glfwCreateWindow(mode->height, mode->width, "Video", monitor, NULL);  
```

`sws_scale(sws_scaler_ctx, av_frame->data, av_frame->linesize, 0, av_frame->height, dest, dest_linesize);`

i got an error in sws_scale function. segmentation fault.
i am following youtube tutorial as you mentioned about scaling video why it's generate error as segmentation fault. if data frame is scale according to given scale then it shouldn't be problem.

regards

**Comment by bmewj** [comment]
Hey man, it's hard to know from what you've given me what exactly is wrong. Are you using my video_reader functions as is or have you copied just the parts of the video reader that you need? If it's the former can you show me how you're calling my code, if it's the latter can you show me all the code you've got? I'm sure I can help if you show me a bit more.

**Comment by Nirmal1313** [comment]
@bartjoyce  hey man,

I am just using your code as learning purpose for video rendering in OpenGL. So, i was trying make some changes and try to if i have big i didn't want to define windows size every time when i run code in different monitor it could be detect dynamically according screen resolution  so i  code for full screen mode as future references. 
```
    glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
    glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 3);
    glfwWindowHint(GLFW_RESIZABLE, GL_FALSE);
    glfwWindowHint(GLFW_OPENGL_FORWARD_COMPAT, GL_TRUE);
    glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);
 
   GLFWmonitor* monitor = glfwGetPrimaryMonitor();
   const GLFWvidmode* mode = glfwGetVideoMode(monitor);
   glfwWindowHint(GLFW_RED_BITS, mode->redBits);
   glfwWindowHint(GLFW_GREEN_BITS, mode->greenBits);
   glfwWindowHint(GLFW_BLUE_BITS, mode->blueBits);
   glfwWindowHint(GLFW_REFRESH_RATE, mode->refreshRate);
  GLFWwindow*  window = glfwCreateWindow(mode->width, mode->height, "ProVision4", monitor, NULL);
```

before
`
 GLFWwindow* window = glfwCreateWindow(1920,1080, "Hello World",  glfwGetPrimaryMonitor(), NULL);`
 
to make sure can i replace this line with GLFWmonitor or not. but the problem accord in sws scaling. every time it scale generate segmentation fault. so i don't know why it generate error for scaling video for monitor.
if you can help or explain me why it has error problem for that that would be grateful.

also, i emailed you my code with to your email address to see if you can find any error their or not.
 also according to my research videoframbuffer scaling can be causing this issue. if you look at some code of mine where i defined `  glfwGetFramebufferSize(window, &window_width, &window_height);`
it can be defined different or something that can scale the video frame.

Regrades,

**Comment by bmewj** [comment]
Okay so I've managed to get your code working on my machine with a couple changes, but it plays a video in full screen mode as expected. I can't manage to reproduce your segmentation fault bug 😞

What's noteworthy is that I had to remove your window hints regarding the context version and OpenGL profile. It ended up looking like this:

```C++
    // glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
    // glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 3);
    glfwWindowHint(GLFW_RESIZABLE, GL_FALSE);
    // glfwWindowHint(GLFW_OPENGL_FORWARD_COMPAT, GL_TRUE);
    // glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);

    GLFWmonitor* monitor = glfwGetPrimaryMonitor();
    GLFWvidmode* mode = const_cast<GLFWvidmode *>(glfwGetVideoMode(monitor));
    glfwWindowHint(GLFW_RED_BITS, mode->redBits);
    glfwWindowHint(GLFW_GREEN_BITS, mode->greenBits);
    glfwWindowHint(GLFW_BLUE_BITS, mode->blueBits);
    glfwWindowHint(GLFW_REFRESH_RATE, mode->refreshRate);
    window = glfwCreateWindow(mode->width, mode->height, "Demo Video", monitor, NULL);
```

The fact that I had to remove those hints to get things working suggests to me that it's your particular version of OpenGL or GLFW that does not support the kind of texture you want to make.

What OS and machine are you building this on?

**Comment by Nirmal1313** [comment]
ok. i am using fedora 31 with linux version 
> 5.4.7-200.fc31.x86_64

which has following specification 

> OpenGL version: 4.5 (Core Profile) Mesa 19.2.8
> GLSL version: 4.50
> Vendor: Intel Open Source Technology Center
> Renderer: Mesa DRI Intel(R) HD Graphics 620 (Kaby Lake GT2) 

So, second thing is can please update code in github so i can understand where did you make change in code. i am struggling this issue since 1 week. it will helpful for to understand scale video framing in sws scale.
what is your thoughts or suggestion about this error?
